// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// IMPORTANT: com.njaridepro.owner must be registered in Firebase Console
/// (jaride-pro project) to get the Android App ID.
/// After registering, replace REGISTER_IN_FIREBASE_CONSOLE with the real App ID
/// and download the google-services.json to android/app/
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Register com.njaridepro.owner in Firebase Console (jaride-pro project)
  // then replace appId value below with the generated Android App ID
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWXkyRu5fIX-wxCy1E9_Nx0FqnVvKvKL0',
    appId: 'REGISTER_IN_FIREBASE_CONSOLE', // TODO: get from Firebase Console
    messagingSenderId: '872495882111',
    projectId: 'jaride-pro',
    databaseURL: 'https://jaride-pro-default-rtdb.firebaseio.com',
    storageBucket: 'jaride-pro.firebasestorage.app',
  );

  // TODO: Register com.njaridepro.owner in Firebase Console for iOS as well
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWXkyRu5fIX-wxCy1E9_Nx0FqnVvKvKL0',
    appId: 'REGISTER_IN_FIREBASE_CONSOLE', // TODO: get from Firebase Console
    messagingSenderId: '872495882111',
    projectId: 'jaride-pro',
    databaseURL: 'https://jaride-pro-default-rtdb.firebaseio.com',
    storageBucket: 'jaride-pro.firebasestorage.app',
    iosBundleId: 'com.njaridepro.owner',
  );
}
